### ISSUE TITLE
Cursor at the end of the email

### ISSUE THREAD

**Issue by Filbuntu** [isshiki/ReFwdFormatter#9]
Thanks a lot for the helpful add-on!
When an email response window opens and the ">" prefix was removed from the quote, the cursor is placed at the end of the email.
Would it be possible the place the cursor at the top of the email? 
Usually the response is written at the beginning of the email and therefore it would be convenient to be able to just to start to type at the rest place.
Thanks for considering this if an implementation is possible.

**Comment by isshiki** [comment]
Fixed in v2.143.0.
Added setting for caret position after formatting: Above quote / Below quote / Select quote (default: Above).
Works for both HTML and plain text replies.

Note: Thunderbird per-account quote placement is not used to avoid requiring additional privileged APIs.

**Comment by Filbuntu** [comment]
Thanks a lot! I just tested it and it works with me! This is great and improves the work flow significantly!

**Comment by Filbuntu** [comment]
Unfortunately I realised that it interferes with this add-on I also rely on:
caligraf/ChangeQuote Wiki — https://github.com/caligraf/ChangeQuote/wiki
https://addons.thunderbird.net/fr/thunderbird/addon/changequote/
The headers of the reply email can not be adjusted anymore ... 
It does not matter where the cursor is placed (above/below/...).
Any hint what I could do differently?
If not, I would prefer the behaviour before this change 🫣😊. Sorry for the trouble.
UPDATE: I  switched back to version 2.136.0 for now.

**Comment by isshiki** [comment]
Hi, thanks for the report!

Good to hear that reverting to v2.136.0 solves it for now.

For reference: starting with v2.143.1, I added an option in this add-on's settings to disable caret positioning.
If you try updating again in the future, enabling that option may prevent interference with ChangeQuote.

Hope this helps.

**Comment by Filbuntu** [comment]
Thank you for the quick update! 
I just tried disabling caret positioning with v2.143.1 but unfortunately it does not do the trick. The headers can still not be changed with ChangeQuote anymore  (TB one line header to Outlook 4-5 lines header).
But I could revert to v2.136.0 again and it works again :). But I have to remember, too, that the cursor is at the end of the email which I am still learning :).

**Comment by isshiki** [comment]
Hi Filbuntu,

Thanks for the detailed feedback and for testing v2.143.1.
I prepared a test build that should address the ChangeQuote header issue:

https://github.com/isshiki/ReFwdFormatter/blob/master/bin/refwdformatter-2.143.2.xpi

Could you please try this version and let me know if it works with ChangeQuote?
If it fixes the issue, I’ll proceed with the release.

Thanks again!

**Comment by Filbuntu** [comment]
Hi isshiki

Thank you so much for even another update! Quick testing reveals it works! I will continue to use (and test) it and report if there would be an issue.

Warm greetings to Japan and thanks again!

**Comment by isshiki** [comment]
Hi Filbuntu,

Great — thanks for confirming! I’ll proceed with the 2.143.2 release.
Please let me know if anything comes up.

Warm greetings to you too, and thanks again!
